### ISSUE TITLE
ERROR , JSON-RPC  getblocktemplate (call with {"rules": ["segwit"]}) 

### ISSUE THREAD

**Issue by kolet** [tecracoin/ccminer#1]
hey there , i am trying to use ccminer as solo miner, (dont mind the algo) , btc core is open with this setting

> 
>  Expose the RPC/JSON API
> server=1
> 
>  Activate the wallet in Testnet mode
> 
> 
>  Allow only local machine to access bitcoind
> rpcallowip=127.0.0.1
> rpcbind=127.0.0.1:8332
> 
> 
>   RPC Port to use - comment out for Testnet
>  rpcport=8332
> 
>  RPC Username and password
> rpcuser=bit
> rpcpassword=xxx
> 

when running ccminer 
ccminer.exe -a x17 -o http://127.0.0.1:8332 --coinbase-addr=my-legacy-address-here  -u bit -p xxx -i 20 -d 0 --debug --no-longpoll --no-getwork --no-stratum --no-gbt

and this is the error that i am getting .

> JSON-RPC call failed: getblocktemplate must be called with the segwit rule set (call with {"rules": ["segwit"]})
> get_work failed, retry after 2 seconds
> JSON-RPC call failed: getblocktemplate must be called with the segwit rule set (call with {"rules": ["segwit"]})
> get_work failed, retry after 2 seconds

i tried to solve it for hours with out any success .
what am i doing wrong , and how can i fix it. 
thank you

**Comment by kolet** [comment]
https://user-images.githubusercontent.com/17353839/113496090-d1f48880-94fe-11eb-9bcc-a8ea07bec21e.mp4

**Comment by djm34** [comment]
well you need to check what informations send you the wallet in getblocktemplate and how to issue a correct getblocktemplate to that wallet, how to build a correct block header so it will be accepted through blocksubmit.

All this is coin dependent... and not related to tecracoin. 
I am closing that issue as it isn't related to tecracoin.
